version: "3"
services:
  # used to simulate AWS environment stack locally
  localstack:
    container_name: "__project_name__-localstack"
    build:
      context: ./docker/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    working_dir: /
    environment:
      - MAIN_CONTAINER_NAME=localstack
      - EAGER_SERVICE_LOADING=false
      - SERVICES=lambda,s3,sns,sqs,iam,apigateway,ecr # SERVICES variable is ignored if EAGER_SERVICE_LOADING=0
      - LS_LOG=debug
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - DEFAULT_REGION=eu-central-1
      - LOCALSTACK_API_KEY= # only required for Pro
      - LAMBDA_TRUNCATE_STDOUT=20000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - STACK_NAME=serverless-framework
      - LAMBDA_REMOTE_DOCKER=false
      - ENVIRONMENT=local
      - NODE_ENV=local
      # CUSTOM ENVS for our AWS stack:

    volumes:
      - "./docker/localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/app"