name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run test

      - name: Upload core test coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/core/.coverage/clover.xml
          flags: core

      - name: Upload router test coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/router/.coverage/clover.xml
          flags: router

      - name: Upload aws-lambda test coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/aws-lambda/.coverage/clover.xml
          flags: aws-lambda
